title: awesome-robomaster
description: ğŸ¤– ğŸ¦¾ å…³äºæœºç”²å¤§å¸ˆRoboMasterå¤§èµ›ï¼Œä»¥åŠæœºå™¨äººå¼€å‘ç›¸å…³å¼€æºé¡¹ç›®æ±‡æ€»åˆé›†

url: https://robomaster-oss.github.io/awesome-robomaster

#logo: "logo.png"
#favicon_ico: "facicon.jpeg"


aux_links:
  Github: https://github.com/robomaster-oss/awesome-robomaster

plugins:
  - jekyll-remote-theme

remote_theme: https://github.com/just-the-docs/just-the-docs